[project.theme]
variant = "modern"
features = [
    "content.code.copy",
    "content.code.annotate",
    "search.highlight",
    "navigation.instant",
    "navigation.instant.progress",
    "navigation.tracking",
    "navigation.path",
    # "navigation.sections",
    # "navigation.tabs",
]
logo = "img/favicon.ico"
favicon = "img/favicon.ico"

[project]
site_name = "Fink/ZTF Documentation"
repo_name = "fink-broker"
repo_url = "https://github.com/astrolabsoftware/fink-broker"
copyright = "Copyright &copy; 2018-26 <a href='https://fink-broker.org'>Fink team</a>."
nav = [
  { Home = "index.md" },
  { "Fink in a nutshell" = [
      { "Science Roadmap" = "broker/roadmap.md" },
      { "Technological consideration" = "broker/infrastructure.md" },
    ]},
  { Science = [
      { "Fink science modules" = "broker/science_modules.md" },
      { "Fink filters" = "broker/filters.md" },
      { "Classification" = "broker/classification.md" },
      { "Accessing alert data" = "broker/services_summary.md" }
    ]},
  { Services = [
      { Overview = "broker/science_modules.md" },
      { "REST API" = [
         # { "Cheat Sheet" = "services/search/cheatsheet.md" },
          { "Getting started" = "services/search/getting_started.md" },
          { "Search by name" = "services/search/objectid.md" },
          { "Search by class" = "services/search/classsearch.md" },
          { "Conesearch" = "services/search/conesearch.md" },
          { "Search by Solar System object name" = "services/search/solar_system.md" },
          { "Resolving astronomical names" = "services/search/resolver.md" },
          { "Image data" = "services/search/imagesearch.md" },
          { "Statistics" = "services/search/statistics.md" },
          { "Columns, blocks and tags definition" = "services/search/definitions.md" },
          { "Space awareness" = "services/search/tracklet.md" },
          { "Multi-messenger" = "services/search/gw.md" },
          { "Anomaly detection" = "services/search/anomaly_detection.md" },
          { "Troubleshooting" = "services/search/troubleshooting.md" }
        ]},
        { "Livestream" = "services/livestream.md" },
        { "Data Transfer" = "services/data_transfer.md" },
        { "Fink bots" = "services/bots.md" },
        { "Fink client" = "services/fink_client.md" },
        { "Xmatch" = "services/xmatch.md" },
        { "TOM Fink" = "services/tom_fink.md" },
        { "Troubleshooting" = "troubleshooting.md" },

    ]},
  { "Developer corner" = [
      { "Source code" = "source-code.md" },
      { "Release Notes" = "release-notes.md" },
      { "Contributing" = "contributing.md" },
      { "Alert schemas" = "developers/schemas.md" },
      { "Designing a science module" = "developers/science_module_tutorial.md" },
      { "Designing a filter" = "developers/filter_tutorial.md" },
      { "Testing Fink" = "developers/testing_fink.md" },
    ]},
  
]
extra_css = [
    "assets/stylesheets/extra.css",
    "https://unpkg.com/katex@0/dist/katex.min.css"
]
extra_javascript = [
    "javascripts/katex.js",
    "https://unpkg.com/katex@0/dist/katex.min.js",
    "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js"
]

[project.extra.status]
new = "Recently added"

[project.markdown_extensions.admonition]
[project.markdown_extensions.tables]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.def_list]
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.blocks.caption]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.tabbed.slugify]
object = "pymdownx.slugs.slugify"
kwds = { case = "lower" }
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]


# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"
primary = "deep orange"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "deep blue"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
primary = "deep orange"

[project.markdown_extensions.pymdownx.arithmatex]
generic = true
